version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ${POSTGRES_CONTAINER:-myproject-postgres-dev}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    container_name: ${REDIS_CONTAINER:-myproject-redis-dev}
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  adminer:
    image: adminer:4-standalone
    container_name: ${ADMINER_CONTAINER:-myproject-adminer-dev}
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
  
volumes:
  postgres_data:
  redis_data: