// packages/shared-types/src/enums/eventTypes.enum.ts

/**
 * Tous les types d'événements Discord
 * Conserve les événements existants + ajoute les nouveaux pour Phase 1
 */
export enum EventType {
  // ==========================================
  // ÉVÉNEMENTS EXISTANTS (Gardés tels quels)
  // ==========================================
  
  // Général
  READY = 'READY',
  ERROR = 'ERROR',
  WARN = 'WARN',
  DEBUG = 'DEBUG',

  // Messages
  MESSAGE_CREATE = 'MESSAGE_CREATE',
  MESSAGE_UPDATE = 'MESSAGE_UPDATE',
  MESSAGE_DELETE = 'MESSAGE_DELETE',
  MESSAGE_DELETE_BULK = 'MESSAGE_DELETE_BULK',

  // Réactions
  MESSAGE_REACTION_ADD = 'MESSAGE_REACTION_ADD',
  MESSAGE_REACTION_REMOVE = 'MESSAGE_REACTION_REMOVE',
  MESSAGE_REACTION_REMOVE_ALL = 'MESSAGE_REACTION_REMOVE_ALL',
  MESSAGE_REACTION_REMOVE_EMOJI = 'MESSAGE_REACTION_REMOVE_EMOJI',

  // Membres
  GUILD_MEMBER_ADD = 'GUILD_MEMBER_ADD',
  GUILD_MEMBER_REMOVE = 'GUILD_MEMBER_REMOVE',
  GUILD_MEMBER_UPDATE = 'GUILD_MEMBER_UPDATE',
  GUILD_BAN_ADD = 'GUILD_BAN_ADD',
  GUILD_BAN_REMOVE = 'GUILD_BAN_REMOVE',

  // Rôles
  ROLE_CREATE = 'ROLE_CREATE',
  ROLE_DELETE = 'ROLE_DELETE',
  ROLE_UPDATE = 'ROLE_UPDATE',

  // Salons (channels)
  CHANNEL_CREATE = 'CHANNEL_CREATE',
  CHANNEL_DELETE = 'CHANNEL_DELETE',
  CHANNEL_UPDATE = 'CHANNEL_UPDATE',
  CHANNEL_PINS_UPDATE = 'CHANNEL_PINS_UPDATE',

  // Guildes (serveurs)
  GUILD_CREATE = 'GUILD_CREATE',
  GUILD_DELETE = 'GUILD_DELETE',
  GUILD_UPDATE = 'GUILD_UPDATE',
  GUILD_LIST = 'GUILD_LIST',
  GUILD_SYNC = 'GUILD_SYNC',
  GUILD_UNAVAILABLE = 'GUILD_UNAVAILABLE',

  // Événements vocaux _ Connexions/Déconnexions
  VOICE_CHANNEL_JOIN = 'VOICE_CHANNEL_JOIN',
  VOICE_CHANNEL_LEAVE = 'VOICE_CHANNEL_LEAVE',
  VOICE_CHANNEL_MOVE = 'VOICE_CHANNEL_MOVE',
  VOICE_STATE_UPDATE = 'VOICE_STATE_UPDATE',

  // Événements vocaux _ Actions de modération
  VOICE_MUTE = 'VOICE_MUTE',
  VOICE_UNMUTE = 'VOICE_UNMUTE',
  VOICE_DEAFEN = 'VOICE_DEAFEN',
  VOICE_UNDEAFEN = 'VOICE_UNDEAFEN',

  // Événements vocaux _ Actions utilisateur
  VOICE_SELF_MUTE = 'VOICE_SELF_MUTE',
  VOICE_SELF_DEAFEN = 'VOICE_SELF_DEAFEN',
  VOICE_STREAMING = 'VOICE_STREAMING',
  VOICE_VIDEO = 'VOICE_VIDEO',

  // Présence / statut
  PRESENCE_UPDATE = 'PRESENCE_UPDATE',
  USER_UPDATE = 'USER_UPDATE',
  TYPING_START = 'TYPING_START',

  // Invitations
  INVITE_CREATE = 'INVITE_CREATE',
  INVITE_DELETE = 'INVITE_DELETE',

  // Interactions (slash commands, boutons, etc.)
  INTERACTION_CREATE = 'INTERACTION_CREATE',

  // Emojis
  EMOJI_CREATE = 'EMOJI_CREATE',
  EMOJI_DELETE = 'EMOJI_DELETE',
  EMOJI_UPDATE = 'EMOJI_UPDATE',

  // Threads
  THREAD_CREATE = 'THREAD_CREATE',
  THREAD_UPDATE = 'THREAD_UPDATE',
  THREAD_DELETE = 'THREAD_DELETE',
  THREAD_LIST_SYNC = 'THREAD_LIST_SYNC',
  THREAD_MEMBER_UPDATE = 'THREAD_MEMBER_UPDATE',
  THREAD_MEMBERS_UPDATE = 'THREAD_MEMBERS_UPDATE',

  // Webhooks
  WEBHOOKS_UPDATE = 'WEBHOOKS_UPDATE',

  // AutoMod
  AUTO_MODERATION_ACTION_EXECUTION = 'AUTO_MODERATION_ACTION_EXECUTION',
  AUTO_MODERATION_RULE_CREATE = 'AUTO_MODERATION_RULE_CREATE',
  AUTO_MODERATION_RULE_DELETE = 'AUTO_MODERATION_RULE_DELETE',
  AUTO_MODERATION_RULE_UPDATE = 'AUTO_MODERATION_RULE_UPDATE',

  // Stickers
  GUILD_STICKER_CREATE = 'GUILD_STICKER_CREATE',
  GUILD_STICKER_UPDATE = 'GUILD_STICKER_UPDATE',
  GUILD_STICKER_DELETE = 'GUILD_STICKER_DELETE',

  // Guild Scheduled
  GUILD_SCHEDULED_EVENT_CREATE = 'GUILD_SCHEDULED_EVENT_CREATE',
  GUILD_SCHEDULED_EVENT_UPDATE = 'GUILD_SCHEDULED_EVENT_UPDATE',
  GUILD_SCHEDULED_EVENT_DELETE = 'GUILD_SCHEDULED_EVENT_DELETE',
  GUILD_SCHEDULED_EVENT_USER_ADD = 'GUILD_SCHEDULED_EVENT_USER_ADD',
  GUILD_SCHEDULED_EVENT_USER_REMOVE = 'GUILD_SCHEDULED_EVENT_USER_REMOVE',

  // Stage
  STAGE_INSTANCE_CREATE = 'STAGE_INSTANCE_CREATE',
  STAGE_INSTANCE_UPDATE = 'STAGE_INSTANCE_UPDATE',
  STAGE_INSTANCE_DELETE = 'STAGE_INSTANCE_DELETE',

  //Integration
  GUILD_INTEGRATIONS_UPDATE = 'GUILD_INTEGRATIONS_UPDATE',


  // ==========================================
  // NOUVEAUX ÉVÉNEMENTS (Phase 1)
  // ==========================================
  
  INVITE_USE = 'INVITE_USE',
  // Audit Log
  GUILD_AUDIT_LOG_ENTRY_CREATE = 'GUILD_AUDIT_LOG_ENTRY_CREATE',
  
  METRICS_SNAPSHOT = 'METRICS_SNAPSHOT',  // Nouveau : snapshot de métriques (messages, vocal, réactions)
  MEMBER_ACTIVITY_SNAPSHOT = 'MEMBER_ACTIVITY_SNAPSHOT',  // Nouveau : activité détaillée par membre
  
  
  // XP/Levels
  XP_GAIN = 'XP_GAIN',
  LEVEL_UP = 'LEVEL_UP',
}