auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

# Configuration de la rétention des logs
limits_config:
  retention_period: 24h  # Garder les logs pendant 24h seulement
  ingestion_rate_mb: 10  # Max 10MB/sec par stream
  ingestion_burst_size_mb: 20  # Burst jusqu'à 20MB
  max_query_length: 721h  # Permettre les requêtes sur 30 jours max

# Compaction automatique pour nettoyer les vieux logs
compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 10m  # Vérifier toutes les 10 minutes
  retention_enabled: true  # Activer la suppression automatique
  retention_delete_delay: 2h  # Délai avant suppression définitive
  retention_delete_worker_count: 150

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

# Améliorer les performances des requêtes
query_range:
  align_queries_with_step: true
  cache_results: true
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

# Limites par tenant (dans notre cas, pas de multi-tenant)
chunk_store_config:
  max_look_back_period: 24h  # Ne pas regarder au-delà de 24h

# Configuration des logs de Loki lui-même
table_manager:
  retention_deletes_enabled: true
  retention_period: 24h